# Generated by Django 2.1.3 on 2018-12-17 11:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Titulo', models.CharField(max_length=50)),
                ('FechaEstrenoVideo', models.CharField(max_length=50)),
                ('IMDbURL', models.CharField(max_length=50)),
                ('Categorias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 17, 12, 41, 13, 530300))),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_recomendacion.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Sexo', models.CharField(max_length=2)),
                ('Ocupacion', models.CharField(max_length=50)),
                ('CodigoPostal', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_recomendacion.Usuario'),
        ),
    ]
