# Generated by Django 2.1.3 on 2018-12-17 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_recomendacion', '0006_auto_20181217_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='peliculas',
            field=models.ManyToManyField(through='sistema_recomendacion.Puntuacion', to='sistema_recomendacion.Pelicula'),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 17, 13, 10, 14, 864988)),
        ),
    ]
